# Generated by Django 5.0.3 on 2024-03-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_commentimage_user_postimage_user_commentdislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumb',
            field=models.ImageField(default='default_category.jpg', upload_to='categories_pics/'),
        ),
    ]
