# Generated by Django 5.0.3 on 2024-03-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_postimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image_replace_text',
        ),
    ]
