# Generated by Django 5.0.3 on 2024-03-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
